### ISSUE TITLE
Colon in | text block

### ISSUE THREAD

**Issue by almays** [djabraham/vscode-yaml-validation#3]
I am having yaml files with texts.
Texts can be multiline, include markdown. I screen out the texts with `|` thing.
```
En: |
  Some text: continuation of the text. 
```
In this case `Some text` is colorized as a key. But actually due to `|` it is going to be parsed as part of the text.

Yaml2json converter, for example, interpretes this syntax as expected:
```
{
  "En": "Some text: continuation of the text. \n"
}
```

But yaml colorizer mistakenly takes `:` in this case at key/value delimiter.

**Comment by djabraham** [comment]
Colorization is actually handled by a built in vscode extension. The extension appears to be shared with most supported file formats, so there may be limitations with regard to syntax complexity. I would recommend opening an issue there, if it isn't already documented. 

As a workaround, quoting strings of this nature seems to fix the colorization issue. Ultimately, the ability to interpret the file depends on the lib that is doing the loading for the app's consumption. 

https://github.com/Microsoft/vscode/tree/master/extensions/yaml
