### ISSUE TITLE
Should error for duplicate keys

### ISSUE THREAD

**Issue by samsch** [djabraham/vscode-yaml-validation#4]
The validator seems to ignore duplicate keys.

This code should error:
```yaml
a: thing1
a: thing2
```
But it does not.

**Comment by djabraham** [comment]
Confirmed locally.

Wonder how long that's been going on. I think this used to work, but the only constant is change.

**Comment by adamvoss** [comment]
@samsch [`vscode-yaml`](https://marketplace.visualstudio.com/items?itemName=adamvoss.yaml) will issue a warning (same severity as is issued in JSON files) making switching extensions an option for gaining this functionality.

**Comment by djabraham** [comment]
Closing, this extension was retired.
